module.exports = {
  KEYS: function(obj){
    var a = "";
    for (var key in obj) {
        a += key
    };
    return a == "" ? undefined : a;
  },
  MODULE_HOST : '',
  MODULE_PATH : {

  },
  MODE_LABEL_MAP: {
    "actionscript":"ActionScript","ada":"Ada","apache_conf":"ApacheConf","applescript":"AppleScript","text":"Visual Basic","assembly_x86":"Assembly","batchfile":"Batchfile","c_cpp":"OpenCL","csharp":"C#","clojure":"Clojure","coffee":"CoffeeScript","lisp":"Racket","css":"CSS","d":"D","dart":"Dart","elixir":"Elixir","erlang":"Erlang","golang":"Go","php":"PHP","haml":"Haml","haskell":"Haskell","html":"Kit","ini":"INI","io":"Io","jade":"Jade","java":"Java","javascript":"JSON5","json":"JSON","smarty":"Smarty","less":"Less","liquid":"Liquid","livescript":"LiveScript","lua":"Lua","makefile":"Makefile","markdown":"RMarkdown","matlab":"Matlab","objectivec":"Objective-C++","ocaml":"OCaml","pascal":"Pascal","perl":"Perl6","powershell":"PowerShell","prolog":"Prolog","python":"Sage","r":"R","rdoc":"RDoc","rhtml":"RHTML","ruby":"Ruby","rust":"Rust","sass":"Sass","scala":"Scala","scheme":"Scheme","sh":"Shell","sql":"SQL","tcl":"Tcl","tex":"TeX","typescript":"TypeScript","xquery":"XQuery","yaml":"YAML"
  },
  LABEL_MODE_MAP: {
    "ActionScript":"actionscript","Ada":"ada","ApacheConf":"apache_conf","AppleScript":"applescript","ASP":"text","Assembly":"assembly_x86","Awk":"text","Batchfile":"batchfile","C":"c_cpp","C#":"csharp","C++":"c_cpp","CLIPS":"text","Clojure":"clojure","CMake":"text","CoffeeScript":"coffee","Common Lisp":"lisp","CSS":"css","Cython":"text","D":"d","Dart":"dart","E":"text","Elixir":"elixir","Emacs Lisp":"lisp","Erlang":"erlang","F#":"text","FORTRAN":"text","Go":"golang","Gradle":"text","Hack":"php","Haml":"haml","Haskell":"haskell","HTML":"html","HTML+PHP":"php","HTTP":"text","Inform 7":"text","INI":"ini","Io":"io","Jade":"jade","Java":"java","JavaScript":"javascript","JSON":"json","JSON5":"javascript","Kit":"html","Latte":"smarty","Less":"less","Liquid":"liquid","LiveScript":"livescript","Lua":"lua","M":"lisp","Makefile":"makefile","Markdown":"markdown","Matlab":"matlab","Nginx":"text","NumPy":"text","Objective-C":"objectivec","Objective-C++":"objectivec","OCaml":"ocaml","OpenCL":"c_cpp","Pascal":"pascal","Perl":"perl","Perl6":"perl","PHP":"php","PowerShell":"powershell","Processing":"text","Prolog":"prolog","Python":"python","Python traceback":"text","R":"r","Racket":"lisp","RDoc":"rdoc","RHTML":"rhtml","RMarkdown":"markdown","Ruby":"ruby","Rust":"rust","Sage":"python","SAS":"text","Sass":"sass","Scala":"scala","Scaml":"text","Scheme":"scheme","Self":"text","Shell":"sh","Smalltalk":"text","Smarty":"smarty","SQL":"sql","Standard ML":"text","Swift":"text","Tcl":"tcl","TeX":"tex","Text":"text","Turing":"text","TypeScript":"typescript","VimL":"text","Visual Basic":"text","XQuery":"xquery","YAML":"yaml"
  },
  LANG_OPTIONS: [
    {value: "ActionScript", label: "ActionScript"},
    {value: "Ada", label: "Ada"},
    {value: "ApacheConf", label: "ApacheConf"},
    {value: "AppleScript", label: "AppleScript"},
    {value: "ASP", label: "ASP"},
    {value: "Assembly", label: "Assembly"},
    {value: "Awk", label: "Awk"},
    {value: "Batchfile", label: "Batchfile"},
    {value: "C", label: "C"},
    {value: "C#", label: "C#"},
    {value: "C++", label: "C++"},
    {value: "CLIPS", label: "CLIPS"},
    {value: "Clojure", label: "Clojure"},
    {value: "CMake", label: "CMake"},
    {value: "CoffeeScript", label: "CoffeeScript"},
    {value: "Common Lisp", label: "Common Lisp"},
    {value: "CSS", label: "CSS"},
    {value: "Cython", label: "Cython"},
    {value: "D", label: "D"},
    {value: "Dart", label: "Dart"},
    {value: "E", label: "E"},
    {value: "Elixir", label: "Elixir"},
    {value: "Emacs Lisp", label: "Emacs Lisp"},
    {value: "Erlang", label: "Erlang"},
    {value: "F#", label: "F#"},
    {value: "FORTRAN", label: "FORTRAN"},
    {value: "Go", label: "Go"},
    {value: "Gradle", label: "Gradle"},
    {value: "Hack", label: "Hack"},
    {value: "Haml", label: "Haml"},
    {value: "Haskell", label: "Haskell"},
    {value: "HTML", label: "HTML"},
    {value: "HTML+PHP", label: "HTML+PHP"},
    {value: "HTTP", label: "HTTP"},
    {value: "Inform 7", label: "Inform 7"},
    {value: "INI", label: "INI"},
    {value: "Io", label: "Io"},
    {value: "Jade", label: "Jade"},
    {value: "Java", label: "Java"},
    {value: "JavaScript", label: "JavaScript"},
    {value: "JSON", label: "JSON"},
    {value: "JSON5", label: "JSON5"},
    {value: "Kit", label: "Kit"},
    {value: "Latte", label: "Latte"},
    {value: "Less", label: "Less"},
    {value: "Liquid", label: "Liquid"},
    {value: "LiveScript", label: "LiveScript"},
    {value: "Lua", label: "Lua"},
    {value: "M", label: "M"},
    {value: "Makefile", label: "Makefile"},
    {value: "Markdown", label: "Markdown"},
    {value: "Matlab", label: "Matlab"},
    {value: "Nginx", label: "Nginx"},
    {value: "NumPy", label: "NumPy"},
    {value: "Objective-C", label: "Objective-C"},
    {value: "Objective-C++", label: "Objective-C++"},
    {value: "OCaml", label: "OCaml"},
    {value: "OpenCL", label: "OpenCL"},
    {value: "Pascal", label: "Pascal"},
    {value: "Perl", label: "Perl"},
    {value: "Perl6", label: "Perl6"},
    {value: "PHP", label: "PHP"},
    {value: "PowerShell", label: "PowerShell"},
    {value: "Processing", label: "Processing"},
    {value: "Prolog", label: "Prolog"},
    {value: "Python", label: "Python"},
    {value: "Python traceback", label: "Python traceback"},
    {value: "R", label: "R"},
    {value: "Racket", label: "Racket"},
    {value: "RDoc", label: "RDoc"},
    {value: "RHTML", label: "RHTML"},
    {value: "RMarkdown", label: "RMarkdown"},
    {value: "Ruby", label: "Ruby"},
    {value: "Rust", label: "Rust"},
    {value: "Sage", label: "Sage"},
    {value: "SAS", label: "SAS"},
    {value: "Sass", label: "Sass"},
    {value: "Scala", label: "Scala"},
    {value: "Scaml", label: "Scaml"},
    {value: "Scheme", label: "Scheme"},
    {value: "Self", label: "Self"},
    {value: "Shell", label: "Shell"},
    {value: "Smalltalk", label: "Smalltalk"},
    {value: "Smarty", label: "Smarty"},
    {value: "SQL", label: "SQL"},
    {value: "Standard ML", label: "Standard ML"},
    {value: "Swift", label: "Swift"},
    {value: "Tcl", label: "Tcl"},
    {value: "TeX", label: "TeX"},
    {value: "Text", label: "Text"},
    {value: "Turing", label: "Turing"},
    {value: "TypeScript", label: "TypeScript"},
    {value: "VimL", label: "VimL"},
    {value: "Visual Basic", label: "Visual Basic"},
    {value: "XQuery", label: "XQuery"},
    {value: "YAML", label: "YAML"}],
}
